## Das Numpy Modul - numerisches Python

In [6]:
""" Spannung und Strom sind als Listen gegeben. Die Leistung soll berechnet werden """
voltages = [5.0, 5.1, 4.9]
currents = [0.2, 0.21, 0.19]

powers = []
for i in range(len(voltages)):
    powers.append(voltages[i] * currents[i])

print(powers)

print(voltages)
print(currents)

[1.0, 1.071, 0.931]
[5.0, 5.1, 4.9]
[0.2, 0.21, 0.19]


In [8]:
import numpy as np

voltages_np = np.array(voltages)
currents_np = np.array(currents)

print(voltages_np)
print(currents_np)

print(type(voltages_np))
print(type(currents_np))

powers_np = voltages_np * currents_np
print(powers_np)

[5.  5.1 4.9]
[0.2  0.21 0.19]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[1.    1.071 0.931]


In [11]:
# Ohne numpy

signal = [1, 2, 3, 4]
scaled_signal = []
for i in signal:
    scaled_signal.append(i * 2)

print(scaled_signal)
# Mit numpy
signal_np = np.array(signal)
scaled_signal = signal_np * 2

print(scaled_signal)

[2, 4, 6, 8]
[2 4 6 8]


In [13]:
""" Filtern von Messdaten """
filtered = []
for voltage in voltages:
    if voltage > 5.0:
        filtered.append(voltage)
print(filtered)
# Mit numpy
voltages_np = np.array(voltages)
filtered_np = voltages_np[voltages_np > 5.0]

print(filtered_np)

[5.1]
[5.1]


In [ ]:
""" Mittelwert berechnen """

values = [1, 2, 3, 4]

mittelwert = sum(values) / len(values)
print(mittelwert)

# Mit numpy
values_np = np.array(values)
# values_np = np.array([.1, .2, .3])
np.array
mittelwert_np = np.mean(values_np)

print(mittelwert_np)


2.5
2.5


In [22]:
""" Zeitachse für Simulation """
t = []
step = 0.1
value = 0

while value <= 10:
    t.append(round(value, 2))
    value += step

print(t)

# Mit numpy
t_np = np.linspace(0, 10, 100)
print(t_np)

[0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6.0, 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7.0, 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9, 8.0, 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9.0, 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9, 10.0]
[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040

In [ ]:
""" Mathematische Funktionen """

import math

values = [0, 1, 2, 3]
result = []
for value in values:
    result.append(math.sin(value))

print(result)

# Mit numpy
values_np = np.array(values)
result_np = np.sin(values_np)

print(result_np)

[0.0, 0.8414709848078965, 0.9092974268256817, 0.1411200080598672]
[0.         0.84147098 0.90929743 0.14112001]
